CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);
CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);
CREATE TABLE topics
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_topics PRIMARY KEY (id)
);

ALTER TABLE topics
    ADD CONSTRAINT uc_topics_title UNIQUE (title);
CREATE TABLE messages
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    topic_id  BIGINT                                  NOT NULL,
    content   VARCHAR(255)                            NOT NULL,
    timestamp BYTEA                                   NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_TOPIC FOREIGN KEY (topic_id) REFERENCES topics (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);
CREATE TABLE topics
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_topics PRIMARY KEY (id)
);

ALTER TABLE topics
    ADD CONSTRAINT uc_topics_title UNIQUE (title);
CREATE TABLE messages
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    topic_id  BIGINT                                  NOT NULL,
    content   VARCHAR(255)                            NOT NULL,
    timestamp BYTEA                                   NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_TOPIC FOREIGN KEY (topic_id) REFERENCES topics (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
CREATE TABLE topics
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_topics PRIMARY KEY (id)
);

ALTER TABLE topics
    ADD CONSTRAINT uc_topics_title UNIQUE (title);
CREATE TABLE messages
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    topic_id  BIGINT                                  NOT NULL,
    content   VARCHAR(255)                            NOT NULL,
    timestamp BYTEA                                   NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_TOPIC FOREIGN KEY (topic_id) REFERENCES topics (id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

